id: 123
user: eq19
span: span-104
title: eQuantum
baseurl: /syntax
repository: ObjectModules/syntax
action: ObjectModules/parser/actions/runs/15062257331
description: ₠Quantum Project

#debug:
#  dist: false
#  compress: true
#  shortcodes: true

lsi: false
incremental: true
highlighter: rouge
plugins_dir: _plugins

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - vendor/
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [9, 5]
  pinned: [maps, feed, lexer, parser, syntax, grammar, steps, bash, store, gtm, jekyll, alzheimer]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
